name: Security & License check

on:
  pull_request:
    branches: ["main"]
    paths:
      - "Cargo.lock"
      - "Cargo.toml"
      - ".github/workflows/deny.yaml"
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  cargo-deny:
    name: Cargo Deny
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v7

      - name: Run cargo-deny check
        uses: EmbarkStudios/cargo-deny-action@v2
        with:
          command: check
          arguments: advisories bans
